// Build-time codegen: writes src/version.ts with the package version so the
// SDK can report sdkVersion without importing package.json at runtime (which is
// not portable under Cloudflare Workers bundling).
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const version = pkg.version ?? '0.0.0'

const contents = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.
export const SDK_VERSION = '${version}'
`

mkdirSync(join(root, 'src'), { recursive: true })
writeFileSync(join(root, 'src', 'version.ts'), contents)
process.stderr.write(`[gen-version] wrote src/version.ts (SDK_VERSION=${version})\n`)
